name: Prace
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: innerspacetrainings/Prace.js@master
        with:
          configuration-path: .github/prace.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
